"""Frozen ``/v1`` wire contract shared by the CLI and the platform (issue #71).

This package is the single owner of the machine boundary between the two
Sprint-1 tracks: neither may invent a field, route or error semantic outside
it. The models here are the generator of ``schemas/v1`` and of the OpenAPI
document, so the FastAPI application must satisfy them rather than produce
them (docs/engineering/schema-evolution.md, SPEC-015 REQ-1508).
"""

from ai_stp_contracts.auth import (
    DeviceAuthorizationRequest,
    DeviceAuthorizationResponse,
    DeviceTokenRequest,
    DeviceTokenResponse,
    OAuthCallbackResult,
    OAuthProvider,
)
from ai_stp_contracts.catalog import (
    CatalogReactionList,
    CatalogReactionState,
    CatalogSupport,
    CatalogSupportEvidence,
    CatalogTrust,
    CatalogTrustLane,
    CatalogUsageMetrics,
    ComponentDetail,
    ComponentListResponse,
    ComponentSearchRequest,
    ComponentSummary,
    ComponentVersionResponse,
    GitHubMetadata,
    PublicLifecycle,
    SetupContextBudget,
    SetupContextBudgetQuery,
    SetupDetail,
    SetupListResponse,
    SetupSearchRequest,
    SetupSummary,
    SetupVersionResponse,
    SupportState,
    SupportTier,
    VersionListEntry,
)
from ai_stp_contracts.health import (
    CheckStatus,
    LivenessResponse,
    ReadinessChecks,
    ReadinessResponse,
)
from ai_stp_contracts.http import (
    API_BASE_PATH,
    API_VERSION,
    CURSOR_PATTERN,
    ETAG_HEADER,
    IDEMPOTENCY_KEY_HEADER,
    IDEMPOTENCY_KEY_PATTERN,
    IF_MATCH_HEADER,
    OPERATION_ID_HEADER,
    PAGE_SIZE_DEFAULT,
    PAGE_SIZE_MAX,
    REQUEST_ID_HEADER,
    SCHEMA_VERSION,
    SCHEMA_VERSION_HEADER,
    Cursor,
    IdempotencyKey,
    PageInfo,
    PageSize,
    Timestamp,
    http_status_for,
    strict_request_object,
)
from ai_stp_contracts.identity import (
    AccountPrivacyUpdate,
    AccountProfile,
    DetectedHarness,
    DeviceListResponse,
    DeviceRecord,
    DeviceRevokeRequest,
    DeviceRevokeResponse,
    DeviceState,
    DeviceSummary,
    LinkedIdentity,
)

__all__ = [
    "API_BASE_PATH",
    "API_VERSION",
    "CURSOR_PATTERN",
    "ETAG_HEADER",
    "IDEMPOTENCY_KEY_HEADER",
    "IDEMPOTENCY_KEY_PATTERN",
    "IF_MATCH_HEADER",
    "OPERATION_ID_HEADER",
    "PAGE_SIZE_DEFAULT",
    "PAGE_SIZE_MAX",
    "REQUEST_ID_HEADER",
    "SCHEMA_VERSION",
    "SCHEMA_VERSION_HEADER",
    "AccountPrivacyUpdate",
    "AccountProfile",
    "CatalogReactionList",
    "CatalogReactionState",
    "CatalogSupport",
    "CatalogSupportEvidence",
    "CatalogTrust",
    "CatalogTrustLane",
    "CatalogUsageMetrics",
    "CheckStatus",
    "ComponentDetail",
    "ComponentListResponse",
    "ComponentSearchRequest",
    "ComponentSummary",
    "ComponentVersionResponse",
    "Cursor",
    "DetectedHarness",
    "DeviceAuthorizationRequest",
    "DeviceAuthorizationResponse",
    "DeviceListResponse",
    "DeviceRecord",
    "DeviceRevokeRequest",
    "DeviceRevokeResponse",
    "DeviceState",
    "DeviceSummary",
    "DeviceTokenRequest",
    "DeviceTokenResponse",
    "GitHubMetadata",
    "IdempotencyKey",
    "LinkedIdentity",
    "LivenessResponse",
    "OAuthCallbackResult",
    "OAuthProvider",
    "PageInfo",
    "PageSize",
    "PublicLifecycle",
    "ReadinessChecks",
    "ReadinessResponse",
    "SetupContextBudget",
    "SetupContextBudgetQuery",
    "SetupDetail",
    "SetupListResponse",
    "SetupSearchRequest",
    "SetupSummary",
    "SetupVersionResponse",
    "SupportState",
    "SupportTier",
    "Timestamp",
    "VersionListEntry",
    "http_status_for",
    "strict_request_object",
]
