"""Frozen ``/v1`` wire contract shared by the CLI and the platform (issue #71).

This package is the single owner of the machine boundary between the two
Sprint-1 tracks: neither may invent a field, route or error semantic outside
it. The models here are the generator of ``schemas/v1`` and of the OpenAPI
document, so the FastAPI application must satisfy them rather than produce
them (docs/engineering/schema-evolution.md, SPEC-015 REQ-1508).

The names below load on first use, not with the package. Every
``ai_stp_contracts.<module>`` import runs this file first, and importing the
seven modules behind these names here cost every CLI invocation about 0.35s
before it reached the one model it needed (docs/engineering/cli-performance.md).
Type checkers read the same names from the ``TYPE_CHECKING`` block.
"""

from importlib import import_module
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from ai_stp_contracts.auth import (
        DeviceApproveRequest,
        DeviceApproveResponse,
        DeviceAuthorizationRequest,
        DeviceAuthorizationResponse,
        DeviceTokenRequest,
        DeviceTokenResponse,
        LegalOnboardingCompleteRequest,
        LegalOnboardingStatus,
        OAuthCallbackResult,
        OAuthProvider,
    )
    from ai_stp_contracts.catalog import (
        CatalogAuthorListResponse,
        CatalogAuthorOption,
        CatalogReactionList,
        CatalogReactionState,
        CatalogSupport,
        CatalogSupportEvidence,
        CatalogTrust,
        CatalogTrustLane,
        CatalogUsageMetrics,
        ComponentContextBudget,
        ComponentDetail,
        ComponentListResponse,
        ComponentSearchRequest,
        ComponentSummary,
        ComponentVersionResponse,
        GitHubMetadata,
        PrivateVersionResponse,
        PublicLifecycle,
        SetupContextBudget,
        SetupContextBudgetQuery,
        SetupDetail,
        SetupListResponse,
        SetupSearchRequest,
        SetupSummary,
        SetupVersionResponse,
        SupportState,
        SupportTier,
        VerificationFilter,
        VersionListEntry,
    )
    from ai_stp_contracts.context import (
        CAPABILITY_ACTIONS,
        CAPABILITY_RESOURCES,
        ActiveContext,
        CapabilityProjection,
        OrganizationListResponse,
        OrganizationSummary,
        ProjectConflictResolutionRequest,
        ProjectLinkPlanRequest,
        ProjectLinkPlanResponse,
        ProjectLinkProposalRequest,
        ProjectLinkRequest,
        ProjectLinkResponse,
        ProjectRevisionPullResponse,
        ProjectRevisionPushRequest,
        ProjectRevisionPushResponse,
        ProjectRevisionReceipt,
        ProjectRevisionView,
        ProjectSyncApplyRequest,
        ProjectSyncPlanRequest,
        ProjectSyncPlanResponse,
        ProjectUnlinkPlanRequest,
        ProjectUnlinkPlanResponse,
        ProjectUnlinkRequest,
        ProviderProjectObservationRequest,
    )
    from ai_stp_contracts.corporate import (
        CorporateAuditEntry,
        CorporateAuditExport,
        CorporateAuditList,
        CorporateAuditQuery,
        CorporateBinding,
        CorporateBindingList,
        CorporateBindingRequest,
        CorporateBindingUpdateRequest,
        CorporateBootstrapRequest,
        CorporateCatalogUsage,
        CorporateCatalogUsageList,
        CorporateCatalogUsageQuery,
        CorporateContext,
        CorporateDeleteRequest,
        CorporateDeleteResult,
        CorporateJobTitleCreateRequest,
        CorporateJobTitleList,
        CorporateJobTitleUpdateRequest,
        CorporateJobTitleView,
        CorporateMember,
        CorporateMemberCreateRequest,
        CorporateMemberList,
        CorporateMembershipAssignment,
        CorporateMembershipAssignmentRequest,
        CorporateMemberUpdateRequest,
        CorporateOrganization,
        CorporateProjectCreateRequest,
        CorporateProjectList,
        CorporateProjectUpdateRequest,
        CorporateProjectView,
        CorporateRoleCreateRequest,
        CorporateRoleList,
        CorporateRoleUpdateRequest,
        CorporateRoleView,
        CorporateServicePrincipalCreateRequest,
        CorporateServicePrincipalList,
        CorporateServicePrincipalUpdateRequest,
        CorporateServicePrincipalView,
        CorporateTeamCreateRequest,
        CorporateTeamList,
        CorporateTeamUpdateRequest,
        CorporateTeamView,
    )
    from ai_stp_contracts.health import (
        CheckStatus,
        LivenessResponse,
        ReadinessChecks,
        ReadinessResponse,
    )
    from ai_stp_contracts.http import (
        API_BASE_PATH,
        API_VERSION,
        CURSOR_PATTERN,
        ETAG_HEADER,
        IDEMPOTENCY_KEY_HEADER,
        IDEMPOTENCY_KEY_PATTERN,
        IF_MATCH_HEADER,
        OPERATION_ID_HEADER,
        PAGE_SIZE_DEFAULT,
        PAGE_SIZE_MAX,
        REQUEST_ID_HEADER,
        SCHEMA_VERSION,
        SCHEMA_VERSION_HEADER,
        Cursor,
        IdempotencyKey,
        PageInfo,
        PageSize,
        Timestamp,
        http_status_for,
        strict_request_object,
    )
    from ai_stp_contracts.identity import (
        AccountPrivacyUpdate,
        AccountProfile,
        DetectedHarness,
        DeviceListResponse,
        DeviceRecord,
        DeviceRevokeRequest,
        DeviceRevokeResponse,
        DeviceState,
        DeviceSummary,
        LinkedIdentity,
    )

#: Every re-exported name, by the module that defines it.
_EXPORTS: Final[dict[str, tuple[str, ...]]] = {
    "auth": (
        "DeviceApproveRequest",
        "DeviceApproveResponse",
        "DeviceAuthorizationRequest",
        "DeviceAuthorizationResponse",
        "DeviceTokenRequest",
        "DeviceTokenResponse",
        "LegalOnboardingCompleteRequest",
        "LegalOnboardingStatus",
        "OAuthCallbackResult",
        "OAuthProvider",
    ),
    "catalog": (
        "CatalogAuthorListResponse",
        "CatalogAuthorOption",
        "CatalogReactionList",
        "CatalogReactionState",
        "CatalogSupport",
        "CatalogSupportEvidence",
        "CatalogTrust",
        "CatalogTrustLane",
        "CatalogUsageMetrics",
        "ComponentContextBudget",
        "ComponentDetail",
        "ComponentListResponse",
        "ComponentSearchRequest",
        "ComponentSummary",
        "ComponentVersionResponse",
        "GitHubMetadata",
        "PrivateVersionResponse",
        "PublicLifecycle",
        "SetupContextBudget",
        "SetupContextBudgetQuery",
        "SetupDetail",
        "SetupListResponse",
        "SetupSearchRequest",
        "SetupSummary",
        "SetupVersionResponse",
        "SupportState",
        "SupportTier",
        "VerificationFilter",
        "VersionListEntry",
    ),
    "context": (
        "CAPABILITY_ACTIONS",
        "CAPABILITY_RESOURCES",
        "ActiveContext",
        "CapabilityProjection",
        "OrganizationListResponse",
        "OrganizationSummary",
        "ProjectConflictResolutionRequest",
        "ProjectLinkPlanRequest",
        "ProjectLinkPlanResponse",
        "ProjectLinkProposalRequest",
        "ProjectLinkRequest",
        "ProjectLinkResponse",
        "ProjectRevisionPullResponse",
        "ProjectRevisionPushRequest",
        "ProjectRevisionPushResponse",
        "ProjectRevisionReceipt",
        "ProjectRevisionView",
        "ProjectSyncApplyRequest",
        "ProjectSyncPlanRequest",
        "ProjectSyncPlanResponse",
        "ProjectUnlinkPlanRequest",
        "ProjectUnlinkPlanResponse",
        "ProjectUnlinkRequest",
        "ProviderProjectObservationRequest",
    ),
    "corporate": (
        "CorporateAuditEntry",
        "CorporateAuditExport",
        "CorporateAuditList",
        "CorporateAuditQuery",
        "CorporateBinding",
        "CorporateBindingList",
        "CorporateBindingRequest",
        "CorporateBindingUpdateRequest",
        "CorporateBootstrapRequest",
        "CorporateCatalogUsage",
        "CorporateCatalogUsageList",
        "CorporateCatalogUsageQuery",
        "CorporateContext",
        "CorporateDeleteRequest",
        "CorporateDeleteResult",
        "CorporateJobTitleCreateRequest",
        "CorporateJobTitleList",
        "CorporateJobTitleUpdateRequest",
        "CorporateJobTitleView",
        "CorporateMember",
        "CorporateMemberCreateRequest",
        "CorporateMemberList",
        "CorporateMembershipAssignment",
        "CorporateMembershipAssignmentRequest",
        "CorporateMemberUpdateRequest",
        "CorporateOrganization",
        "CorporateProjectCreateRequest",
        "CorporateProjectList",
        "CorporateProjectUpdateRequest",
        "CorporateProjectView",
        "CorporateRoleCreateRequest",
        "CorporateRoleList",
        "CorporateRoleUpdateRequest",
        "CorporateRoleView",
        "CorporateServicePrincipalCreateRequest",
        "CorporateServicePrincipalList",
        "CorporateServicePrincipalUpdateRequest",
        "CorporateServicePrincipalView",
        "CorporateTeamCreateRequest",
        "CorporateTeamList",
        "CorporateTeamUpdateRequest",
        "CorporateTeamView",
    ),
    "health": (
        "CheckStatus",
        "LivenessResponse",
        "ReadinessChecks",
        "ReadinessResponse",
    ),
    "http": (
        "API_BASE_PATH",
        "API_VERSION",
        "CURSOR_PATTERN",
        "ETAG_HEADER",
        "IDEMPOTENCY_KEY_HEADER",
        "IDEMPOTENCY_KEY_PATTERN",
        "IF_MATCH_HEADER",
        "OPERATION_ID_HEADER",
        "PAGE_SIZE_DEFAULT",
        "PAGE_SIZE_MAX",
        "REQUEST_ID_HEADER",
        "SCHEMA_VERSION",
        "SCHEMA_VERSION_HEADER",
        "Cursor",
        "IdempotencyKey",
        "PageInfo",
        "PageSize",
        "Timestamp",
        "http_status_for",
        "strict_request_object",
    ),
    "identity": (
        "AccountPrivacyUpdate",
        "AccountProfile",
        "DetectedHarness",
        "DeviceListResponse",
        "DeviceRecord",
        "DeviceRevokeRequest",
        "DeviceRevokeResponse",
        "DeviceState",
        "DeviceSummary",
        "LinkedIdentity",
    ),
}

_MODULE_OF: Final[dict[str, str]] = {
    name: module for module, names in _EXPORTS.items() for name in names
}

__all__ = [
    "API_BASE_PATH",
    "API_VERSION",
    "CAPABILITY_ACTIONS",
    "CAPABILITY_RESOURCES",
    "CURSOR_PATTERN",
    "ETAG_HEADER",
    "IDEMPOTENCY_KEY_HEADER",
    "IDEMPOTENCY_KEY_PATTERN",
    "IF_MATCH_HEADER",
    "OPERATION_ID_HEADER",
    "PAGE_SIZE_DEFAULT",
    "PAGE_SIZE_MAX",
    "REQUEST_ID_HEADER",
    "SCHEMA_VERSION",
    "SCHEMA_VERSION_HEADER",
    "AccountPrivacyUpdate",
    "AccountProfile",
    "ActiveContext",
    "CapabilityProjection",
    "CatalogAuthorListResponse",
    "CatalogAuthorOption",
    "CatalogReactionList",
    "CatalogReactionState",
    "CatalogSupport",
    "CatalogSupportEvidence",
    "CatalogTrust",
    "CatalogTrustLane",
    "CatalogUsageMetrics",
    "CheckStatus",
    "ComponentContextBudget",
    "ComponentDetail",
    "ComponentListResponse",
    "ComponentSearchRequest",
    "ComponentSummary",
    "ComponentVersionResponse",
    "CorporateAuditEntry",
    "CorporateAuditExport",
    "CorporateAuditList",
    "CorporateAuditQuery",
    "CorporateBinding",
    "CorporateBindingList",
    "CorporateBindingRequest",
    "CorporateBindingUpdateRequest",
    "CorporateBootstrapRequest",
    "CorporateCatalogUsage",
    "CorporateCatalogUsageList",
    "CorporateCatalogUsageQuery",
    "CorporateContext",
    "CorporateDeleteRequest",
    "CorporateDeleteResult",
    "CorporateJobTitleCreateRequest",
    "CorporateJobTitleList",
    "CorporateJobTitleUpdateRequest",
    "CorporateJobTitleView",
    "CorporateMember",
    "CorporateMemberCreateRequest",
    "CorporateMemberList",
    "CorporateMemberUpdateRequest",
    "CorporateMembershipAssignment",
    "CorporateMembershipAssignmentRequest",
    "CorporateOrganization",
    "CorporateProjectCreateRequest",
    "CorporateProjectList",
    "CorporateProjectUpdateRequest",
    "CorporateProjectView",
    "CorporateRoleCreateRequest",
    "CorporateRoleList",
    "CorporateRoleUpdateRequest",
    "CorporateRoleView",
    "CorporateServicePrincipalCreateRequest",
    "CorporateServicePrincipalList",
    "CorporateServicePrincipalUpdateRequest",
    "CorporateServicePrincipalView",
    "CorporateTeamCreateRequest",
    "CorporateTeamList",
    "CorporateTeamUpdateRequest",
    "CorporateTeamView",
    "Cursor",
    "DetectedHarness",
    "DeviceApproveRequest",
    "DeviceApproveResponse",
    "DeviceAuthorizationRequest",
    "DeviceAuthorizationResponse",
    "DeviceListResponse",
    "DeviceRecord",
    "DeviceRevokeRequest",
    "DeviceRevokeResponse",
    "DeviceState",
    "DeviceSummary",
    "DeviceTokenRequest",
    "DeviceTokenResponse",
    "GitHubMetadata",
    "IdempotencyKey",
    "LegalOnboardingCompleteRequest",
    "LegalOnboardingStatus",
    "LinkedIdentity",
    "LivenessResponse",
    "OAuthCallbackResult",
    "OAuthProvider",
    "OrganizationListResponse",
    "OrganizationSummary",
    "PageInfo",
    "PageSize",
    "PrivateVersionResponse",
    "ProjectConflictResolutionRequest",
    "ProjectLinkPlanRequest",
    "ProjectLinkPlanResponse",
    "ProjectLinkProposalRequest",
    "ProjectLinkRequest",
    "ProjectLinkResponse",
    "ProjectRevisionPullResponse",
    "ProjectRevisionPushRequest",
    "ProjectRevisionPushResponse",
    "ProjectRevisionReceipt",
    "ProjectRevisionView",
    "ProjectSyncApplyRequest",
    "ProjectSyncPlanRequest",
    "ProjectSyncPlanResponse",
    "ProjectUnlinkPlanRequest",
    "ProjectUnlinkPlanResponse",
    "ProjectUnlinkRequest",
    "ProviderProjectObservationRequest",
    "PublicLifecycle",
    "ReadinessChecks",
    "ReadinessResponse",
    "SetupContextBudget",
    "SetupContextBudgetQuery",
    "SetupDetail",
    "SetupListResponse",
    "SetupSearchRequest",
    "SetupSummary",
    "SetupVersionResponse",
    "SupportState",
    "SupportTier",
    "Timestamp",
    "VerificationFilter",
    "VersionListEntry",
    "http_status_for",
    "strict_request_object",
]


def __getattr__(name: str) -> object:
    module = _MODULE_OF.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f"{__name__}.{module}"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
