"""Shared validation for short public text fields."""

from __future__ import annotations

import re
import unicodedata

_ALLOWED_PUNCTUATION = frozenset(".,!?;:'\"()-/+&#%=\n\r ")
_UNSAFE_URI = re.compile(r"(?i)(?<![\w])(?:javascript|data|vbscript):")
_BLOCKED_WORDS: tuple[str, ...] = (
    # Profanity and slurs.
    "бля",
    "блядь",
    "блядство",
    "блядский",
    "гандон",
    "гандоны",
    "говно",
    "говнюк",
    "говнючий",
    "дерьмо",
    "дерьмовый",
    "долбоёб",
    "долбоеб",
    "ебать",
    "ёбать",
    "ебу",  # noqa: RUF001
    "ёбу",
    "ебёт",
    "ебет",
    "ебал",
    "ёбал",
    "ебаный",
    "ёбаный",
    "ебись",
    "ёбись",
    "ебля",
    "ёбля",
    "еблан",
    "ёблан",
    "ебучий",
    "ёбучий",
    "жопа",
    "жопу",
    "жопой",
    "жопы",
    "залупа",
    "манда",
    "мразь",
    "мрази",
    "мудак",
    "мудаки",
    "мудила",
    "нахуй",
    "нахер",
    "пидор",
    "пидоры",
    "пидар",
    "пидары",
    "педик",
    "пизда",
    "пиздец",
    "пизду",
    "пиздой",
    "пизды",
    "пиздатый",
    "пошёл",
    "пошел",
    "уёбок",
    "уебок",
    "уёбанный",
    "уебанный",
    "шлюха",
    "шлюхи",
    "сучка",
    "сука",
    "сучий",
    "сучара",
    "чмо",
    "хуй",
    "хуя",
    "хуйню",
    "хуйня",
    "хуесос",  # noqa: RUF001
    "хер",  # noqa: RUF001
    "херня",
    "херовый",
    "blya",
    "blyat",
    "ebat",
    "hui",
    "khuy",
    "pizda",
    "suka",
    "cunt",
    "dick",
    "dickhead",
    "dicks",
    "bitch",
    "bitches",
    "cock",
    "cocks",
    "asshole",
    "assholes",
    "bastard",
    "bullshit",
    "douche",
    "jackass",
    "fag",
    "fuck",
    "fucked",
    "fucker",
    "fucking",
    "motherfucker",
    "motherfucking",
    "piss",
    "pissing",
    "prick",
    "pussy",
    "shit",
    "slut",
    "sluts",
    "twat",
    "wanker",
    "wanking",
    "whore",
    "whores",
    # Sexual content, platforms, and sexual services.
    "порно",
    "порнография",
    "секс",
    "эротика",
    "эротический",
    "обнажённый",
    "обнаженный",
    "обнажена",
    "обнажено",
    "интим",
    "интимный",
    "интимные",
    "эскорт",
    "проститутка",
    "проституция",
    "путана",
    "онлифанс",
    "camgirl",
    "camboy",
    "escort",
    "hooker",
    "nsfw",
    "onlyfans",
    "porn",
    "pornography",
    "sex",
    "nude",
    "nudity",
    "xxx",
    # Threats and violence.
    "убью",
    "убить",
    "убийство",
    "убийца",
    "убил",
    "убила",
    "убили",
    "умри",
    "сдох",
    "сдохни",
    "зарежу",
    "зарезать",
    "застрелю",
    "застрелить",
    "расстрел",
    "расстрелять",
    "взорву",
    "взорвать",
    "пытка",
    "пытки",
    "пытать",
    "изнасилование",
    "изнасиловать",
    "насилие",
    "нападение",
    "напасть",
    "террор",
    "террорист",
    "угроза",
    "угрожаю",
    "угрожать",
    "уничтожу",
    "уничтожить",
    "расправа",
    "assault",
    "bomb",
    "bombing",
    "destroy",
    "explode",
    "explosion",
    "kill",
    "killing",
    "murder",
    "murderer",
    "rape",
    "shoot",
    "shooting",
    "stab",
    "stabbing",
    "terrorist",
    "terrorism",
    "threat",
    "threaten",
    "torture",
    # Nazism, fascism, hate, and extremist advocacy.
    "нацист",
    "нацисты",
    "нацизм",
    "фашист",
    "фашисты",
    "фашизм",
    "гитлер",
    "свастика",
    "расизм",
    "расист",
    "ксенофоб",
    "геноцид",
    "nazi",
    "nazis",
    "nazism",
    "fascist",
    "fascism",
    "hitler",
    "swastika",
    "racist",
    "racism",
    "xenophobe",
    "xenophobia",
    "genocide",
    "supremacist",
    "supremacy",
    # War and military action.
    "война",
    "войны",
    "военный",
    "военная",
    "военное",
    "военные",
    "боевик",
    "боевые",
    "оружие",
    "солдат",
    "солдаты",
    "фронт",
    "обстрел",
    "обстрелы",
    "ракета",
    "ракеты",
    "бомба",
    "бомбы",
    "взрыв",
    "взрывы",
    "атака",
    "атаки",
    "вторжение",
    "оккупация",
    "мобилизация",
    "снаряд",
    "снаряды",
    "боеприпасы",
    "дрон",
    "дроны",
    "армия",
    "армии",
    "армию",
    "армией",
    "армиями",
    "military",
    "soldier",
    "soldiers",
    "weapon",
    "weapons",
    "missile",
    "missiles",
    "bomb",
    "bombing",
    "explosion",
    "attack",
    "attacks",
    "invasion",
    "occupy",
    "occupation",
    "combat",
    "ammunition",
    "drone",
    "drones",
    "war",
    "warfare",
    "warzone",
    "warship",
)
_BLOCKED_PATTERNS = (
    r"18\+",
    r"only[\s_-]*fans",
    r"онли[\s_-]*фанс",
    r"(?:sex|sexual)[\s_-]*(?:work|service|services)",
    r"adult\s+content",
    r"иди\s+нахуй",
    r"иди\s+нахер",
)
_BLOCKED_CONTENT = re.compile(
    r"(?iu)(?<![\w])(?:"
    + "|".join(re.escape(word) for word in _BLOCKED_WORDS)
    + ("|" if _BLOCKED_PATTERNS else "")
    + "|".join(_BLOCKED_PATTERNS)
    + r")(?![\w])"
)


def validate_public_text(value: str, *, allow_empty: bool = False) -> str:
    """Normalize and validate user-authored public text without reflecting it."""

    if not isinstance(value, str):  # pyright: ignore[reportUnnecessaryIsInstance]
        raise ValueError("text must be a string")
    normalized = unicodedata.normalize("NFC", value)
    try:
        normalized.encode("utf-8")
    except UnicodeEncodeError as error:
        raise ValueError("text must be valid UTF-8") from error
    if any(
        not character.isalnum() and character not in _ALLOWED_PUNCTUATION
        for character in normalized
    ):
        raise ValueError("text contains forbidden characters")
    if _UNSAFE_URI.search(normalized):
        raise ValueError("text contains an unsafe URI")

    normalized = normalized.replace("\r\n", "\n").replace("\r", "\n").strip(" \n")
    if not normalized:
        if allow_empty:
            return ""
        raise ValueError("text must not be empty")
    if _BLOCKED_CONTENT.search(normalized):
        raise ValueError("text contains prohibited content")
    return normalized
