#!/usr/bin/env python3
"""Check documentation frontmatter, links, indexes, Mermaid, freshness, and language.

Run through just rather than directly:

    just docs-static    check
    just docs-gen       regenerate index.md tables

Flags: --template allows {{...}} placeholders, --fix regenerates indexes,
--max-age sets the freshness threshold, and --format github emits runner annotations.

Exit code is 1 when at least one error exists. Warnings do not affect the exit code.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# Documentation directories to check.
DOC_ROOTS = ["docs", "specs"]

# Roots exempt from index and frontmatter rules: only link and markup integrity
# is checked there. The empty list remains part of needs_frontmatter and
# sync_index_tables.
STRUCTURE_EXEMPT: list[str] = []

# Root files: check links, markup, and language, but not frontmatter. Templates
# with a .template suffix are checked like working files; a template with broken
# links should not pass merely because it has not been expanded.
ROOT_DOCS = [
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    "SECURITY.md",
    "QUICKSTART.md",
    "README.template.md",
    "AGENTS.template.md",
    "CLAUDE.template.md",
    "QUICKSTART.template.md",
]

REQUIRED_FRONTMATTER = {"description", "last_verified"}

# An index is required when a directory has more documents than this or has subdirectories.
INDEX_THRESHOLD = 4

MAX_DESCRIPTION_LEN = 200

MERMAID_TYPES = {
    "flowchart",
    "graph",
    "sequenceDiagram",
    "classDiagram",
    "stateDiagram",
    "stateDiagram-v2",
    "erDiagram",
    "journey",
    "gantt",
    "pie",
    "mindmap",
    "timeline",
    "gitGraph",
    "quadrantChart",
    "C4Context",
    "C4Container",
    "C4Component",
    "C4Dynamic",
    "sankey-beta",
    "block-beta",
    "xychart-beta",
}

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)
LINK_RE = re.compile(r"\[([^\]\n]+)\]\(([^)\s]+?)(?:\s+\"[^\"]*\")?\)")
FENCE_RE = re.compile(r"^([ \t]*)(`{3,}|~{3,})[ \t]*([^\s`]*)[ \t]*$")
PLACEHOLDER_RE = re.compile(r"\{\{[^}]*\}\}")
CHECKBOX_RE = re.compile(r"^\s*[-*]\s+\[[ xX]\]\s")
ADR_FILENAME_RE = re.compile(r"^ADR-(\d{4})-[a-z0-9-]+\.md$")
ADR_HEADING_RE = re.compile(r"^# ADR-(\d{4}):\s+\S", re.M)
#: From the H1 to the first `##`. A status lives there; a mention in the body
#: is not one, and counting the body would let any passing reference satisfy
#: the back-reference rule.
ADR_HEAD_RE = re.compile(r"^# ADR-\d{4}.*?(?=^## )", re.S | re.M)
#: The verbs an ADR uses to say it changed another record. Up to four words may
#: sit between the verb and the identifier — "Refines transport in `ADR-0103`" is
#: real, and a regex demanding adjacency silently misses it, which is how the
#: first version of this check under-counted its own subject.
ADR_SUPERSEDES_RE = re.compile(
    r"(Supersedes|Superseded|Replaces|Replaced|Refines|Refined|Supplements|Supplemented"
    r"|Extends|Extended|Continues|Continued|Clarifies|Clarified)"
    r"((?:\s+[^\s`]+){0,4})\s+`?(ADR-\d{4})`?",
    re.IGNORECASE,
)

# The index.md child table is generated between these markers.
TABLE_START = "<!-- CONTENTS: generated by just docs-gen; do not edit manually -->"
TABLE_END = "<!-- END CONTENTS -->"

# Documentation is written in English. Code and links are removed before the
# check because paths, commands, and identifiers are Latin by definition.
MAX_CYRILLIC_RATIO = 0.5
MIN_WORDS = 8
CODE_SPAN_RE = re.compile(r"`[^`]*`")

#: A document named in backticks. Markdown only: other backticked names describe
#: future artifacts rather than repository files.
BACKTICKED_DOCUMENT_RE = re.compile(r"`([A-Za-z0-9_./-]+\.md)`")
MD_LINK_RE = re.compile(r"\[[^\]\n]*\]\([^)]*\)")
IDENTIFIER_RE = re.compile(
    r"\b(?:[A-Z][A-Za-z0-9_/-]*|[a-z]+[_/-][A-Za-z0-9_/-]+|[a-z]+[A-Z][A-Za-z0-9_]*)\b"
)
CYRILLIC_WORD_RE = re.compile(r"[\u0430-\u044f\u0451\u0410-\u042f\u0401]{2,}")
LATIN_WORD_RE = re.compile(r"[a-zA-Z]{2,}")


def tracked_markdown(root: Path) -> list[Path]:
    """Return Markdown that the repository contains: tracked plus new local files.

    New files not covered by ignore are included deliberately so a document is
    checked before its first `git add`, not after.
    """
    try:
        listed = subprocess.run(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", "*.md"],
            cwd=root,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        # Outside a Git checkout, the tree walk remains the only source.
        return sorted(path for path in root.rglob("*.md") if path.is_file())
    return sorted({root / name for name in listed.split("\0") if name and (root / name).is_file()})


@dataclass
class Issue:
    level: str  # error | warning
    path: Path
    line: int
    code: str
    message: str


class Linter:
    def __init__(
        self,
        template_mode: bool,
        max_age: int,
        fix: bool = False,
        root: Path | None = None,
        current_date: dt.date | None = None,
    ) -> None:
        self.template_mode = template_mode
        self.max_age = max_age
        self.fix = fix
        self.root = root or ROOT
        # CI runners use UTC while contributors may be several hours into the
        # next local calendar day. One SHA must not change validity with TZ.
        self.current_date = current_date or dt.datetime.now(dt.UTC).date()
        self._document_names: set[str] | None = None
        self.issues: list[Issue] = []
        self.descriptions: dict[Path, str] = {}

    # -- infrastructure --------------------------------------------------

    def error(self, path: Path, line: int, code: str, message: str) -> None:
        self.issues.append(Issue("error", path, line, code, message))

    def warn(self, path: Path, line: int, code: str, message: str) -> None:
        self.issues.append(Issue("warning", path, line, code, message))

    def collect_files(self) -> list[Path]:
        files: list[Path] = []
        for name in ROOT_DOCS:
            p = ROOT / name
            if p.exists():
                files.append(p)
        for root in DOC_ROOTS:
            base = ROOT / root
            if base.exists():
                files.extend(sorted(base.rglob("*.md")))
        return files

    def needs_frontmatter(self, path: Path) -> bool:
        """Documents carry frontmatter, not short-lived working artifacts.

        A STRUCTURE_EXEMPT root describes itself only through its index; its other
        files are short-lived and do not need individual index entries.
        """
        if path.parent == ROOT:
            return False
        rel = path.relative_to(ROOT)
        if rel.parts[0] in STRUCTURE_EXEMPT:
            return path.name == "index.md" and len(rel.parts) == 2
        return rel.parts[0] in ("docs", "specs") or path.name in ("index.md", "README.md")

    # -- passes -----------------------------------------------------------

    def run(self) -> int:
        files = self.collect_files()

        # First pass: frontmatter and descriptions for index comparisons.
        for path in files:
            text = path.read_text(encoding="utf-8")
            self.check_frontmatter(path, text)

        self.check_adr_identities()
        self.check_adr_chain()

        # Regenerate tables before checking links; otherwise removing a document
        # makes the first run report a stale table that it was about to repair.
        if self.fix:
            self.sync_index_tables()

        # Second pass: everything else, with all file descriptions available.
        for path in files:
            text = path.read_text(encoding="utf-8")
            self.check_links(path, text)
            self.check_backticked_documents(path, text)
            self.check_index_annotations(path, text)
            self.check_mermaid(path, text)
            self.check_state_leak(path, text)
            self.check_language(path, text)
            self.check_index_form(path, text)
            if not self.template_mode:
                self.check_placeholders(path, text)

        self.check_indexes()
        if not self.fix:
            self.sync_index_tables()
        return 0

    def check_frontmatter(self, path: Path, text: str) -> None:
        if not self.needs_frontmatter(path):
            return

        m = FRONTMATTER_RE.match(text)
        if not m:
            self.error(
                path, 1, "FM001", "frontmatter with description and last_verified is missing"
            )
            return

        # Parse with a real YAML parser. Line-based parsing mishandles colons in
        # values and placeholder braces.
        try:
            fields = yaml.safe_load(m.group(1)) or {}
        except yaml.YAMLError as exc:
            self.error(
                path,
                2,
                "FM007",
                f"frontmatter is not valid YAML: {str(exc).splitlines()[0]}. "
                f"Quote values containing special characters",
            )
            return
        if not isinstance(fields, dict):
            self.error(path, 2, "FM007", "frontmatter must be a mapping")
            return

        extra = set(fields) - REQUIRED_FRONTMATTER
        missing = REQUIRED_FRONTMATTER - set(fields)
        if missing:
            self.error(
                path, 2, "FM003", f"required fields are missing: {', '.join(sorted(missing))}"
            )
        if extra:
            self.error(
                path,
                2,
                "FM004",
                f"extra fields: {', '.join(sorted(extra))}. "
                f"Only description and last_verified are allowed",
            )

        description = str(fields.get("description", ""))
        if description:
            self.descriptions[path] = description
            if len(description) > MAX_DESCRIPTION_LEN:
                self.warn(
                    path,
                    2,
                    "FM005",
                    f"description has {len(description)} characters; "
                    f"limit is {MAX_DESCRIPTION_LEN}",
                )
            if not description.endswith("."):
                self.warn(path, 2, "FM006", "description does not end with a period")

        self.check_freshness(path, str(fields.get("last_verified", "")))

    def check_freshness(self, path: Path, value: str) -> None:
        if not value:
            return
        if PLACEHOLDER_RE.search(value):
            if not self.template_mode:
                self.error(path, 3, "FR001", "last_verified is not filled in")
            return
        try:
            verified = dt.date.fromisoformat(value.strip())
        except ValueError:
            self.error(path, 3, "FR002", f"last_verified is not a YYYY-MM-DD date: {value}")
            return
        age = (self.current_date - verified).days
        if age < 0:
            self.error(path, 3, "FR003", f"last_verified is in the future: {value}")
        elif age > self.max_age:
            self.warn(
                path,
                3,
                "FR004",
                f"not checked for {age} days; threshold is {self.max_age}. "
                "Check against code and update the date",
            )

    def check_links(self, path: Path, text: str) -> None:
        for line_no, line in iter_lines_outside_fences(text):
            for match in LINK_RE.finditer(line):
                target = match.group(2)
                if target.startswith(("http://", "https://", "mailto:", "#")):
                    continue
                if PLACEHOLDER_RE.search(target) or "*" in target:
                    continue

                anchor = ""
                if "#" in target:
                    target, anchor = target.split("#", 1)
                if not target:
                    continue

                resolved = (path.parent / target).resolve()
                if not resolved.exists():
                    self.error(
                        path,
                        line_no,
                        "LN001",
                        f"link points nowhere: {match.group(2)}",
                    )
                    continue

                if anchor and resolved.suffix == ".md":
                    self.check_anchor(path, line_no, resolved, anchor, match.group(2))

    def check_backticked_documents(self, path: Path, text: str) -> None:
        """Require every backticked document name to resolve to an existing file.

        check_links handles Markdown links but cannot see document names written
        in backticks. Only `.md` names are checked; other backticked names can
        describe future contract artifacts rather than repository files.
        """
        for line_no, line in iter_lines_outside_fences(text):
            for match in BACKTICKED_DOCUMENT_RE.finditer(line):
                reference = match.group(1)
                if PLACEHOLDER_RE.search(reference) or "*" in reference:
                    continue
                if reference.startswith("/"):
                    # A leading slash is a web-served route rather than a file in
                    # this tree. Checking it as a pathlib path could resolve to a
                    # same-named file at the filesystem root.
                    continue
                candidates = (
                    path.parent / reference,
                    path.parent.parent / reference,
                    self.root / reference,
                    self.root / "docs" / reference,
                )
                if any(candidate.exists() for candidate in candidates):
                    continue
                # Documents may name neighboring files, while CLAUDE.md and
                # SKILL.md are real files outside docs/. Check existence rather
                # than location; the rule catches names with no file behind them.
                if Path(reference).name in self.document_names():
                    continue
                self.error(
                    path,
                    line_no,
                    "LN002",
                    f"backticked document does not exist: {reference}",
                )

    def document_names(self) -> set[str]:
        """Build the repository Markdown filename set once.

        Git provides the list rather than a tree walk. Build output such as a
        generated `.next/agents.md` directory must not make a nonexistent
        document reference pass; Git already knows what belongs to the repository.
        """
        if self._document_names is None:
            self._document_names = {path.name for path in tracked_markdown(self.root)}
        return self._document_names

    def check_index_annotations(self, path: Path, text: str) -> None:
        """Require a document link used as a list item to have an annotation.

        The rule applies to every document, not only indexes: a link list is a
        menu from which an agent chooses what to open. Links in prose and tables
        are not checked because their surrounding text or column supplies context.
        """
        for line_no, item in iter_list_items(text):
            match = LINK_RE.search(item)
            if not match:
                continue
            target = match.group(2).split("#")[0]
            if target.startswith(("http://", "https://", "mailto:")) or not target:
                continue
            if PLACEHOLDER_RE.search(target) or "*" in target:
                continue
            resolved = (path.parent / target).resolve()
            if not resolved.exists() or resolved.suffix != ".md":
                continue
            self.check_annotation(path, line_no, item, match, resolved)

    def check_anchor(self, path: Path, line_no: int, target: Path, anchor: str, raw: str) -> None:
        text = target.read_text(encoding="utf-8")
        slugs = {slugify(m.group(1)) for m in re.finditer(r"^#{1,6}\s+(.+)$", text, re.M)}
        if anchor.lower() not in slugs:
            self.warn(path, line_no, "LN002", f"anchor not found in target file: {raw}")

    def check_annotation(
        self, path: Path, line_no: int, item: str, match: re.Match[str], target: Path
    ) -> None:
        """Require a description of what the linked document contains and when to read it."""
        tail = item[match.end() :]
        if not tail.startswith(":"):
            self.error(
                path,
                line_no,
                "AN001",
                f"index link has no annotation: {match.group(2)}. "
                f"Format: `[label](relative-path): description. Read when ...`",
            )
            return

        annotation = tail[1:].strip()
        if len(annotation) < 10:
            self.error(path, line_no, "AN002", f"annotation is too short: {annotation!r}")
            return

        expected = self.descriptions.get(target)
        if expected and not annotations_agree(annotation, expected):
            self.warn(
                path,
                line_no,
                "AN003",
                f"annotation differs from the target file description.\n"
                f"    in index: {annotation[:80]}\n"
                f"    in file:  {expected[:80]}",
            )

    def check_language(self, path: Path, text: str) -> None:
        """Documentation prose is written in English.

        Only prose is counted. Code, links, and markup are removed because paths,
        commands, and identifiers are Latin by definition.
        """
        # Skip frontmatter: it contains service fields rather than reader prose.
        m = FRONTMATTER_RE.match(text)
        skip_until = text[: m.end()].count("\n") if m else 0

        for line_no, line in iter_lines_outside_fences(text):
            if line_no <= skip_until:
                continue
            stripped = line.strip()
            if not stripped or stripped.startswith(("|", ">", "<!--")):
                continue
            # Remove the full link, which usually contains a path.
            prose = MD_LINK_RE.sub(" ", CODE_SPAN_RE.sub(" ", stripped))
            prose = IDENTIFIER_RE.sub(" ", prose)
            cyr = len(CYRILLIC_WORD_RE.findall(prose))
            lat = len(LATIN_WORD_RE.findall(prose))
            if cyr + lat < MIN_WORDS:
                continue
            if cyr / (cyr + lat) >= MAX_CYRILLIC_RATIO:
                self.error(
                    path,
                    line_no,
                    "EN001",
                    "the line is not in English; non-English text is allowed only "
                    "in explicit localized data, paths, commands, and identifiers",
                )

    # -- content table generation ----------------------------------------

    def index_rows(self, index: Path) -> list[str]:
        """Return child table rows: name, description, and frontmatter verification date."""
        rows = []
        children: list[tuple[str, Path]] = []
        for sub in sorted(d for d in index.parent.iterdir() if d.is_dir()):
            child_index = sub / "index.md"
            if child_index.exists():
                children.append((f"{sub.name}/", child_index))
        for doc in sorted(index.parent.glob("*.md")):
            if doc.name != "index.md":
                children.append((doc.name, doc))

        for label, target in children:
            meta = read_frontmatter(target)
            rel = target.relative_to(index.parent).as_posix()
            rows.append(
                f"| [{label}]({rel}) | {meta.get('description', '')} | "
                f"{meta.get('last_verified', '')} |"
            )
        return rows

    def render_table(self, index: Path) -> str:
        rows = self.index_rows(index) or ["| - | empty | - |"]
        return "\n".join(
            [
                TABLE_START,
                "",
                "| Document | Description | Verified |",
                "| -------- | ----- | ------- |",
                *rows,
                "",
                TABLE_END,
            ]
        )

    def sync_index_tables(self) -> None:
        """Build the content table from child frontmatter rather than hand-written rows.

        A hand-written list drifts from the directory as soon as a file is added
        and then confidently misstates what the directory contains.
        """
        for root in DOC_ROOTS:
            # An exempt root owns its own board rather than a document list, so
            # no content table is generated for it.
            if root in STRUCTURE_EXEMPT:
                continue
            base = ROOT / root
            if not base.exists():
                continue
            for index in [base / "index.md", *base.rglob("index.md")]:
                if not index.exists():
                    continue
                text = index.read_text(encoding="utf-8")
                start, end = text.find(TABLE_START), text.find(TABLE_END)
                if start == -1 or end < start:
                    self.error(index, 1, "IX004", "index has no content-table markers")
                    continue
                end += len(TABLE_END)
                fresh = self.render_table(index)
                if text[start:end].strip() == fresh.strip():
                    continue
                if self.fix:
                    index.write_text(
                        text[:start] + fresh + text[end:], encoding="utf-8", newline="\n"
                    )
                else:
                    self.error(
                        index,
                        1,
                        "IX005",
                        "content table differs from the directory; run just docs-gen",
                    )

    def check_index_form(self, path: Path, text: str) -> None:
        """An index consists of frontmatter, a heading, and a generated table.

        Zone rules live in a separate section. An index filled with policy stops
        serving as a table of contents, and its rules drift from their source.
        """
        if path.name != "index.md":
            return
        m = FRONTMATTER_RE.match(text)
        body = text[m.end() :] if m else text
        start = body.find(TABLE_START)
        if start == -1:
            return
        head = body[:start]
        extra = [
            line
            for line in head.split(chr(10))
            if line.strip() and not line.lstrip().startswith("#")
        ]
        if extra:
            self.error(
                path,
                1,
                "IX006",
                f"index has text outside its heading and table: {extra[0][:60]}. "
                f"Zone rules live in docs/documentation, not here",
            )

    def check_indexes(self) -> None:
        for root in DOC_ROOTS:
            if root in STRUCTURE_EXEMPT:
                continue
            base = ROOT / root
            if not base.exists():
                continue
            for directory in [base, *[d for d in base.rglob("*") if d.is_dir()]]:
                docs = [p for p in directory.glob("*.md") if p.name != "index.md"]
                subdirs = [d for d in directory.iterdir() if d.is_dir()]
                index = directory / "index.md"
                if index.exists():
                    continue
                if len(docs) > INDEX_THRESHOLD or subdirs:
                    reason = (
                        f"{len(docs)} documents"
                        if len(docs) > INDEX_THRESHOLD
                        else f"{len(subdirs)} nested directories"
                    )
                    self.error(
                        directory / "index.md",
                        1,
                        "IX001",
                        f"index.md is missing although the directory has {reason}",
                    )

    def check_adr_identities(self) -> None:
        """One accepted ADR number names one file and the same heading.

        An ADR number is the stable reference used by code, specifications and
        operations documentation. Two files sharing it make every short
        reference ambiguous even while both paths remain valid.
        """
        base = self.root / "docs" / "adr"
        if not base.exists():
            return

        owners: dict[str, Path] = {}
        for path in sorted(base.glob("ADR-*.md")):
            match = ADR_FILENAME_RE.fullmatch(path.name)
            if match is None:
                self.error(path, 1, "AD001", "ADR name does not match ADR-NNNN-kebab-case.md")
                continue
            identifier = match.group(1)
            previous = owners.get(identifier)
            if previous is not None:
                self.error(
                    path,
                    1,
                    "AD002",
                    f"ADR-{identifier} is already owned by {previous.name}",
                )
            else:
                owners[identifier] = path

            text = path.read_text(encoding="utf-8")
            heading = ADR_HEADING_RE.search(text)
            if heading is None:
                self.error(path, 1, "AD003", "heading of the form # ADR-NNNN: decision is missing")
            elif heading.group(1) != identifier:
                self.error(
                    path,
                    text[: heading.start()].count("\n") + 1,
                    "AD004",
                    f"heading ADR-{heading.group(1)} does not match the filename ADR-{identifier}",
                )

    def _withheld_adrs(self) -> frozenset[str]:
        """ADR identifiers the publication manifest keeps out of the public tree.

        Read from `release_scripts/public_manifest.toml`, which owns the
        boundary; restating the list here would be the second copy this
        repository forbids. Absent manifest means nothing is withheld, which is
        the honest answer for a tree that does not publish.
        """
        manifest = self.root / "release_scripts" / "public_manifest.toml"
        if not manifest.is_file():
            return frozenset()
        found: set[str] = set()
        section = False
        for line in manifest.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("["):
                section = stripped == "[withheld]"
                continue
            if not section:
                continue
            match = re.search(r"docs/adr/ADR-(\d{4})-", stripped)
            if match:
                found.add(f"ADR-{match.group(1)}")
        return frozenset(found)

    def check_adr_chain(self) -> None:
        """A record that changed another must be findable from the one it changed.

        `AGENTS.md` states the rule: a superseded record is kept and points at
        the one that replaced it. Nothing checked the second half, and a reader
        landing on the older ADR saw an accepted status with no way forward.
        Measured 2026-08-29: ten of fourteen supersession claims were
        one-directional, and two named ADRs the public tree does not carry.

        Only the head region counts — from the H1 to the first `##`. That is
        where a status lives, and a mention buried in the body is not a status.
        """
        base = self.root / "docs" / "adr"
        if not base.exists():
            return
        heads: dict[str, str] = {}
        lines_of: dict[str, Path] = {}
        for path in sorted(base.glob("ADR-*.md")):
            match = ADR_FILENAME_RE.fullmatch(path.name)
            if match is None:
                continue
            identifier = f"ADR-{match.group(1)}"
            text = path.read_text(encoding="utf-8")
            region = ADR_HEAD_RE.search(text)
            heads[identifier] = region.group(0) if region else text[:1200]
            lines_of[identifier] = path

        withheld = self._withheld_adrs()
        for identifier, region in sorted(heads.items()):
            path = lines_of[identifier]
            for verb, _between, target in ADR_SUPERSEDES_RE.findall(region):
                # A withheld record may point at a published one; the published
                # one must not point back. Requiring it would put a reference to
                # a document the public reader cannot open into the published
                # tree, which is the defect this check exists to prevent — one
                # boundary along. The manifest owns which records those are.
                if identifier in withheld and target not in withheld:
                    continue
                if target not in heads:
                    self.error(
                        path,
                        1,
                        "AD005",
                        f"{identifier} says it {verb.lower()} {target}, "
                        f"but {target} is absent from this tree; the reference goes nowhere",
                    )
                    continue
                if identifier not in heads[target]:
                    self.error(
                        path,
                        1,
                        "AD006",
                        f"{identifier} says it {verb.lower()} {target}, "
                        f"but {target} does not report this. Add a back-reference "
                        f"to its status so the replaced record points to its replacement",
                    )

    def check_mermaid(self, path: Path, text: str) -> None:
        for line_no, info, body in iter_fences(text):
            if info != "mermaid":
                continue
            content = [line for line in body if line.strip() and not line.strip().startswith("%%")]
            if not content:
                self.error(path, line_no, "MM001", "empty Mermaid block")
                continue
            first = content[0].strip()
            kind = first.split()[0].rstrip(";") if first.split() else ""
            if kind not in MERMAID_TYPES:
                self.error(
                    path,
                    line_no,
                    "MM002",
                    f"unknown diagram type: {kind!r}; block will not render",
                )
            unbalanced = sum(line.count("[") - line.count("]") for line in content)
            if unbalanced:
                self.warn(path, line_no, "MM003", "unbalanced brackets in Mermaid block")

    def check_state_leak(self, path: Path, text: str) -> None:
        """Progress checklists must not live in docs/."""
        try:
            rel = path.relative_to(ROOT)
        except ValueError:
            return
        if rel.parts[0] != "docs":
            return
        for line_no, line in iter_lines_outside_fences(text):
            if CHECKBOX_RE.match(line):
                self.error(
                    path,
                    line_no,
                    "ST001",
                    "checklist in docs/; task state belongs in the tracker, not documentation",
                )
                return

    def check_placeholders(self, path: Path, text: str) -> None:
        for line_no, line in iter_lines_outside_fences(text):
            if PLACEHOLDER_RE.search(line):
                self.error(
                    path,
                    line_no,
                    "PH001",
                    "unfilled template placeholder",
                )
                return

    # -- output -----------------------------------------------------------

    def report(self) -> int:
        errors = [i for i in self.issues if i.level == "error"]
        warnings = [i for i in self.issues if i.level == "warning"]

        for issue in sorted(self.issues, key=lambda i: (str(i.path), i.line)):
            rel = issue.path.relative_to(ROOT) if issue.path.is_relative_to(ROOT) else issue.path
            mark = "ERROR " if issue.level == "error" else "warning"
            print(f"{mark} {rel}:{issue.line} [{issue.code}] {issue.message}")

        print()
        print(f"Errors: {len(errors)}, warnings: {len(warnings)}")
        return 1 if errors else 0

    def report_github(self) -> int:
        errors = [i for i in self.issues if i.level == "error"]
        for issue in self.issues:
            rel = issue.path.relative_to(ROOT) if issue.path.is_relative_to(ROOT) else issue.path
            kind = "error" if issue.level == "error" else "warning"
            message = issue.message.replace("\n", "%0A")
            print(f"::{kind} file={rel},line={issue.line},title={issue.code}::{message}")
        return 1 if errors else 0


# -- helpers -------------------------------------------------------------


def iter_fences(text: str):
    """Yield (line number, language, body lines) for each code block."""
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        m = FENCE_RE.match(lines[i])
        if m:
            fence = m.group(2)
            info = m.group(3)
            start = i + 1
            body: list[str] = []
            i += 1
            while i < len(lines):
                closing = FENCE_RE.match(lines[i])
                if (
                    closing
                    and closing.group(2)[0] == fence[0]
                    and len(closing.group(2)) >= len(fence)
                    and not closing.group(3)
                ):
                    break
                body.append(lines[i])
                i += 1
            yield start, info, body
        i += 1


def iter_lines_outside_fences(text: str):
    """Yield (line number, line) only outside code blocks."""
    inside = None
    for line_no, line in enumerate(text.split("\n"), start=1):
        m = FENCE_RE.match(line)
        if m:
            marker = m.group(2)
            if inside is None:
                inside = marker
            elif marker[0] == inside[0] and len(marker) >= len(inside) and not m.group(3):
                inside = None
            continue
        if inside is None:
            yield line_no, line


def iter_list_items(text: str):
    """Yield (first line number, item text) for list items.

    Continuation lines are joined because an annotation usually spans multiple
    lines and checking only its first line would miss its content.
    """
    item_start = re.compile(r"^\s*[-*+]\s+")
    lines = list(iter_lines_outside_fences(text))
    i = 0
    while i < len(lines):
        line_no, line = lines[i]
        if item_start.match(line):
            parts = [line]
            j = i + 1
            while j < len(lines):
                nxt_no, nxt = lines[j]
                if nxt_no != lines[j - 1][0] + 1:
                    break
                if not nxt.strip() or item_start.match(nxt) or not nxt.startswith((" ", "	")):
                    break
                parts.append(nxt.strip())
                j += 1
            yield line_no, " ".join(parts)
            i = j
        else:
            i += 1


def read_frontmatter(path: Path) -> dict:
    """Return frontmatter fields parsed by the YAML parser."""
    m = FRONTMATTER_RE.match(path.read_text(encoding="utf-8"))
    if not m:
        return {}
    try:
        fields = yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return {}
    return fields if isinstance(fields, dict) else {}


def slugify(heading: str) -> str:
    text = re.sub(r"[`*_]", "", heading).strip().lower()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    return re.sub(r"[\s]+", "-", text)


def normalize(text: str) -> set[str]:
    words = re.findall(r"\w+", text.lower(), flags=re.UNICODE)
    return {w for w in words if len(w) > 3}


def annotations_agree(annotation: str, description: str) -> bool:
    """Require an index annotation to overlap semantically with file description.

    Exact equality is not required because indexes add a "Read when ..." clause.
    Check that meaningful description words occur in the annotation.
    """
    a, d = normalize(annotation), normalize(description)
    if not d:
        return True
    return len(a & d) / len(d) >= 0.4


def main() -> int:
    # Windows consoles are not UTF-8 by default.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")  # pyright: ignore[reportAttributeAccessIssue]

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--template", action="store_true", help="template mode: {{...}} placeholders are allowed"
    )
    parser.add_argument(
        # 180 days could never fire: measured 2026-08-29, the oldest document in
        # the tree was 26 days old and the whole project was younger than the
        # threshold. A check that cannot reach its own subject reads as
        # protection while examining nothing. 90 is reachable within this
        # project's life and stays a warning, not a gate — age is a weak proxy
        # anyway, and the rules that actually catch a wrong document are the
        # mechanical ones: AD005, AD006, LN001, LN002.
        "--max-age",
        type=int,
        default=90,
        help="last_verified freshness threshold in days",
    )
    parser.add_argument("--fix", action="store_true", help="regenerate content tables in index.md")
    parser.add_argument("--format", choices=["text", "github"], default="text")
    args = parser.parse_args()

    linter = Linter(template_mode=args.template, max_age=args.max_age, fix=args.fix)
    linter.run()
    if args.format == "github":
        return linter.report_github()
    return linter.report()


if __name__ == "__main__":
    sys.exit(main())
