"""Generate one native projection of the canonical Agent Skill per harness.

`docs/agent/harness-projections.md`: one canonical procedure is not copied by
hand. So each projection is a thin native wrapper that points at the canonical
`SKILL.md` and states what its harness expects — the procedure itself exists
once, and a projection cannot carry a stale copy of a command list because it
carries no command list at all.

Run through `just back-gen`; `just back-static` verifies that what is
committed is what this produces.
"""

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Final

ROOT: Final[Path] = Path(__file__).resolve().parents[1]
CANONICAL: Final[Path] = ROOT / "skills" / "canonical" / "ai-stp" / "SKILL.md"
PROJECTIONS: Final[Path] = ROOT / "skills" / "projections"

#: The same files inside the package, so an installed wheel carries them. The
#: repository copy is what a reader edits and links to; this one is what a user
#: actually receives, and `--check` holds the two together. Without it the
#: canonical Skill existed only in a checkout, and the product's primary
#: consumer — the agent — got a binary and no procedure.
PACKAGED: Final[Path] = ROOT / "apps" / "cli" / "src" / "ai_stp_cli" / "skills"

MARKER: Final[str] = "<!-- generated by docs_scripts/skill_projections.py; do not edit -->"


@dataclass(frozen=True)
class Projection:
    """One harness and the native surface it expects."""

    harness_id: str
    directory: str
    filename: str
    surface: str


TARGETS: Final[tuple[Projection, ...]] = (
    Projection(
        "claude-code", "claude-code", "SKILL.md", "Plugin/Skill и явный import через `CLAUDE.md`"
    ),
    Projection("codex", "codex", "SKILL.md", "Plugin/Skill и совместимая инструкция `AGENTS.md`"),
    Projection("pi", "pi", "SKILL.md", "Package, resources, Skill и локальные settings target"),
    Projection("opencode", "opencode", "SKILL.md", "Native Skill, plugin, agent и command"),
    Projection("grok-build", "grok-build", "SKILL.md", "Native marketplace, plugin и Skill"),
    Projection("cursor", "cursor", "SKILL.md", "Plugin с манифестом `.cursor-plugin/plugin.json`"),
    Projection(
        "antigravity",
        "antigravity",
        "SKILL.md",
        "Skill и agent в общем доме Gemini, плагин в `antigravity-cli`",
    ),
)


def render(projection: Projection) -> str:
    """One projection: a pointer, not a copy."""
    return f"""---
name: ai-stp
harness: {projection.harness_id}
description: Нативная проекция канонического Skill ai-stp.
---

{MARKER}

# ai_stp — проекция для {projection.harness_id}

Нативная поверхность этого харнесса: {projection.surface}.

Процедура не дублируется. Канон находится в `skills/canonical/ai-stp/SKILL.md`,
и эта проекция существует, чтобы харнесс нашёл его в ожидаемом для себя месте.

Перечня команд здесь нет намеренно. Он живёт в реестре CLI, а машинная справка
порождается из реестра: начни с `ai-stp doctor --json`, затем возьми команды из
`ai-stp help --agent --json` и вызывай только их.
"""


def packaged_targets() -> dict[Path, Path]:
    """Every file the package must carry, mapped from its repository original."""
    mapping = {CANONICAL: PACKAGED / "canonical" / "SKILL.md"}
    for projection in TARGETS:
        source = PROJECTIONS / projection.directory / projection.filename
        mapping[source] = PACKAGED / "projections" / f"{projection.harness_id}.md"
    return mapping


def write() -> list[Path]:
    written: list[Path] = []
    for projection in TARGETS:
        target = PROJECTIONS / projection.directory / projection.filename
        target.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" как в docs_lint.py и install_hooks.py: без него генератор
        # на Windows пишет CRLF, и каждый локальный прогон показывает пять
        # изменённых проекций, отличающихся только концами строк.
        target.write_text(render(projection), encoding="utf-8", newline="\n")
        written.append(target)
    for source, packaged in packaged_targets().items():
        packaged.parent.mkdir(parents=True, exist_ok=True)
        packaged.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
        written.append(packaged)
    return written


def check() -> list[str]:
    problems: list[str] = []
    if not CANONICAL.exists():
        problems.append(f"canonical skill is missing: {CANONICAL}")
    expected = {PROJECTIONS / p.directory / p.filename for p in TARGETS}
    for projection in TARGETS:
        target = PROJECTIONS / projection.directory / projection.filename
        if not target.exists():
            problems.append(f"projection is missing: {target.relative_to(ROOT)}")
            continue
        if target.read_text(encoding="utf-8") != render(projection):
            problems.append(f"projection drifted from the generator: {target.relative_to(ROOT)}")
    for found in PROJECTIONS.rglob("SKILL.md"):
        if found not in expected:
            problems.append(f"unexpected projection without a generator: {found.relative_to(ROOT)}")

    # The copy a user receives. A checkout that passes every other gate while
    # shipping a wheel without the Skill is exactly what happened before.
    carried = packaged_targets()
    for source, packaged in carried.items():
        if not packaged.exists():
            problems.append(f"the package does not carry: {packaged.relative_to(ROOT)}")
            continue
        if not source.exists():
            continue
        if packaged.read_text(encoding="utf-8") != source.read_text(encoding="utf-8"):
            problems.append(f"the packaged copy drifted: {packaged.relative_to(ROOT)}")
    if PACKAGED.exists():
        for found in PACKAGED.rglob("*.md"):
            if found not in set(carried.values()):
                problems.append(f"the package carries an orphan: {found.relative_to(ROOT)}")
    return problems


def main(argv: list[str] | None = None) -> int:
    arguments = sys.argv[1:] if argv is None else argv
    if "--check" in arguments:
        problems = check()
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1 if problems else 0
    for path in write():
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
