"""Generate native and locale projections of the canonical Agent Skill.

`docs/agent/harness-projections.md` and `ADR-0149`: one canonical procedure is
not copied by hand. A harness projection is that procedure plus harness
metadata and a short native-surface note. It is never a pointer at a
repository path. `just back-gen` writes; `just back-static` checks.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Final

ROOT: Final[Path] = Path(__file__).resolve().parents[1]
CANONICAL: Final[Path] = ROOT / "skills" / "canonical" / "ai-stp"
CANONICAL_SKILL: Final[Path] = CANONICAL / "SKILL.md"
REFERENCES: Final[Path] = CANONICAL / "references"
LOCALE_RU: Final[Path] = CANONICAL / "locale" / "ru"
PROJECTIONS: Final[Path] = ROOT / "skills" / "projections"
PACKAGED: Final[Path] = ROOT / "apps" / "cli" / "src" / "ai_stp_cli" / "skills"

MARKER: Final[str] = "<!-- generated by docs_scripts/skill_projections.py; do not edit -->"
INVOCATION: Final[re.Pattern[str]] = re.compile(r"`(ai-stp [^`\n]+)`")
FRONTMATTER: Final[re.Pattern[str]] = re.compile(r"\A---\n.*?\n---\n", re.S)


@dataclass(frozen=True)
class Projection:
    """One harness and the native surface it expects."""

    harness_id: str
    directory: str
    filename: str
    surface: str


TARGETS: Final[tuple[Projection, ...]] = (
    Projection(
        "claude-code",
        "claude-code",
        "SKILL.md",
        "Plugin/Skill and explicit import through `CLAUDE.md`",
    ),
    Projection("codex", "codex", "SKILL.md", "Plugin/Skill and compatible `AGENTS.md` instruction"),
    Projection("pi", "pi", "SKILL.md", "Package, resources, Skill, and local target settings"),
    Projection("opencode", "opencode", "SKILL.md", "Native Skill, plugin, agent, and command"),
    Projection("grok-build", "grok-build", "SKILL.md", "Native marketplace, plugin, and Skill"),
    Projection("cursor", "cursor", "SKILL.md", "Plugin with `.cursor-plugin/plugin.json` manifest"),
    Projection(
        "antigravity",
        "antigravity",
        "SKILL.md",
        "Skill and agent in Gemini's shared home, with a plugin in `antigravity-cli`",
    ),
)

REFERENCE_NAMES: Final[tuple[str, ...]] = (
    "envelope.md",
    "decisions.md",
    "traps.md",
    "bootstrap.md",
    "onboard.md",
    "account.md",
    "inspect.md",
    "catalog.md",
    "compose.md",
    "install.md",
    "daily.md",
    "recover.md",
    "author.md",
    "provider.md",
    "self.md",
)


def _body(skill_text: str) -> str:
    stripped = FRONTMATTER.sub("", skill_text, count=1)
    return stripped.lstrip()


def render(projection: Projection, *, locale: str = "en") -> str:
    """Harness projection: the procedure plus native-surface metadata."""
    source = CANONICAL_SKILL if locale == "en" else LOCALE_RU / "SKILL.md"
    text = source.read_text(encoding="utf-8")
    locale_line = "" if locale == "en" else '  locale: "ru"\n'
    header = f"""---
name: ai-stp
description: Operate the ai-stp CLI on the {projection.harness_id} native surface.
license: AGPL-3.0-or-later
metadata:
  harness: "{projection.harness_id}"
  source: canonical
{locale_line}---

{MARKER}

Native surface for this harness: {projection.surface}.

"""
    return header + _body(text)


def reference_files(locale: str = "en") -> dict[str, str]:
    root = REFERENCES if locale == "en" else LOCALE_RU / "references"
    return {name: (root / name).read_text(encoding="utf-8") for name in REFERENCE_NAMES}


def packaged_targets() -> dict[Path, Path]:
    """Every file the package must carry, mapped from its repository original."""
    mapping = {CANONICAL_SKILL: PACKAGED / "canonical" / "SKILL.md"}
    for name in REFERENCE_NAMES:
        mapping[REFERENCES / name] = PACKAGED / "canonical" / "references" / name
    mapping[LOCALE_RU / "SKILL.md"] = PACKAGED / "locales" / "ru" / "SKILL.md"
    for name in REFERENCE_NAMES:
        mapping[LOCALE_RU / "references" / name] = PACKAGED / "locales" / "ru" / "references" / name
    for projection in TARGETS:
        source = PROJECTIONS / projection.directory / projection.filename
        mapping[source] = PACKAGED / "projections" / f"{projection.harness_id}.md"
        ru = PROJECTIONS / projection.directory / "locale" / "ru" / projection.filename
        mapping[ru] = PACKAGED / "projections" / f"{projection.harness_id}.ru.md"
    return mapping


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def write() -> list[Path]:
    written: list[Path] = []
    for projection in TARGETS:
        target = PROJECTIONS / projection.directory / projection.filename
        _write_text(target, render(projection))
        written.append(target)
        ru = PROJECTIONS / projection.directory / "locale" / "ru" / projection.filename
        _write_text(ru, render(projection, locale="ru"))
        written.append(ru)
    for source, packaged in packaged_targets().items():
        _write_text(packaged, source.read_text(encoding="utf-8"))
        written.append(packaged)
    return written


def _invocations(text: str) -> set[str]:
    return set(INVOCATION.findall(text))


def _locale_loss() -> list[str]:
    problems: list[str] = []
    if not (LOCALE_RU / "SKILL.md").exists():
        return [f"russian locale skill is missing: {LOCALE_RU / 'SKILL.md'}"]
    english = _invocations(CANONICAL_SKILL.read_text(encoding="utf-8"))
    russian = _invocations((LOCALE_RU / "SKILL.md").read_text(encoding="utf-8"))
    if english - russian:
        problems.append(
            "russian locale skill dropped invocations: " + ", ".join(sorted(english - russian))
        )
    for name in REFERENCE_NAMES:
        en_path = REFERENCES / name
        ru_path = LOCALE_RU / "references" / name
        if not ru_path.exists():
            problems.append(f"russian locale reference is missing: {ru_path.relative_to(ROOT)}")
            continue
        dropped = _invocations(en_path.read_text(encoding="utf-8")) - _invocations(
            ru_path.read_text(encoding="utf-8")
        )
        if dropped:
            problems.append(f"russian {name} dropped invocations: " + ", ".join(sorted(dropped)))
    return problems


def check() -> list[str]:
    problems: list[str] = []
    if not CANONICAL_SKILL.exists():
        problems.append(f"canonical skill is missing: {CANONICAL_SKILL}")
    for name in REFERENCE_NAMES:
        path = REFERENCES / name
        if not path.exists():
            problems.append(f"canonical reference is missing: {path.relative_to(ROOT)}")
    problems.extend(_locale_loss())
    expected = set()
    for projection in TARGETS:
        target = PROJECTIONS / projection.directory / projection.filename
        expected.add(target)
        if not target.exists():
            problems.append(f"projection is missing: {target.relative_to(ROOT)}")
        elif target.read_text(encoding="utf-8") != render(projection):
            problems.append(f"projection drifted from the generator: {target.relative_to(ROOT)}")
        ru = PROJECTIONS / projection.directory / "locale" / "ru" / projection.filename
        expected.add(ru)
        if not ru.exists():
            problems.append(f"russian projection is missing: {ru.relative_to(ROOT)}")
        elif ru.read_text(encoding="utf-8") != render(projection, locale="ru"):
            problems.append(
                f"russian projection drifted from the generator: {ru.relative_to(ROOT)}"
            )
    for found in PROJECTIONS.rglob("SKILL.md"):
        if found not in expected:
            problems.append(f"unexpected projection without a generator: {found.relative_to(ROOT)}")

    carried = packaged_targets()
    for source, packaged in carried.items():
        if not packaged.exists():
            problems.append(f"the package does not carry: {packaged.relative_to(ROOT)}")
            continue
        if not source.exists():
            continue
        if packaged.read_text(encoding="utf-8") != source.read_text(encoding="utf-8"):
            problems.append(f"the packaged copy drifted: {packaged.relative_to(ROOT)}")
    if PACKAGED.exists():
        for found in PACKAGED.rglob("*.md"):
            if found not in set(carried.values()):
                problems.append(f"the package carries an orphan: {found.relative_to(ROOT)}")
    return problems


def main(argv: list[str] | None = None) -> int:
    arguments = sys.argv[1:] if argv is None else argv
    if "--check" in arguments:
        problems = check()
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1 if problems else 0
    for path in write():
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
