"""Shared source contracts and GitHub/package/local resolvers (SPEC-057, ADR-0139)."""

from ai_stp_sources.catalog_match import (
    CatalogMatchInput,
    CatalogReplacementSuggestion,
    catalog_coordinate_from_passport,
    suggest_catalog_replacement,
)
from ai_stp_sources.coordinates import canonical_github_source, canonicalize_source
from ai_stp_sources.definition import (
    DEFINITION_V1,
    DEFINITION_V2,
    EmbeddedDraft,
    FrozenDefinition,
    decode_embedded_artifact,
    definition_has_embedded,
    freeze_setup_definition,
    local_component_identity,
    source_links_for_snapshot,
    try_parse_setup_definition,
    unpack_component_tree,
    validate_setup_definition,
)
from ai_stp_sources.errors import (
    AMBIGUOUS_DISTRIBUTION,
    CATALOG_COLLISION,
    FLOATING_FROZEN_SOURCE,
    INCOMPLETE_PASSPORT,
    INTEGRITY_MISMATCH,
    INVALID_SOURCE,
    MISSING_EMBEDDED_REF,
    PROHIBITED_REDISTRIBUTION,
    UNAVAILABLE_SOURCE,
    UNSAFE_ARCHIVE,
    UNSUPPORTED_SOURCE,
    SourceError,
)
from ai_stp_sources.git import FetchFn, GithubHttpResponse
from ai_stp_sources.models import (
    CatalogIntent,
    CratesEvidence,
    GitIntent,
    GoEvidence,
    NpmEvidence,
    PackageIntent,
    PathIntent,
    PubEvidence,
    PypiEvidence,
    SourceIntent,
    SourceSnapshot,
)
from ai_stp_sources.resolve import resolve_source, validate_frozen_snapshot

__all__ = [
    "AMBIGUOUS_DISTRIBUTION",
    "CATALOG_COLLISION",
    "DEFINITION_V1",
    "DEFINITION_V2",
    "FLOATING_FROZEN_SOURCE",
    "INCOMPLETE_PASSPORT",
    "INTEGRITY_MISMATCH",
    "INVALID_SOURCE",
    "MISSING_EMBEDDED_REF",
    "PROHIBITED_REDISTRIBUTION",
    "UNAVAILABLE_SOURCE",
    "UNSAFE_ARCHIVE",
    "UNSUPPORTED_SOURCE",
    "CatalogIntent",
    "CatalogMatchInput",
    "CatalogReplacementSuggestion",
    "CratesEvidence",
    "EmbeddedDraft",
    "FetchFn",
    "FrozenDefinition",
    "GitIntent",
    "GithubHttpResponse",
    "GoEvidence",
    "NpmEvidence",
    "PackageIntent",
    "PathIntent",
    "PubEvidence",
    "PypiEvidence",
    "SourceError",
    "SourceIntent",
    "SourceSnapshot",
    "canonical_github_source",
    "canonicalize_source",
    "catalog_coordinate_from_passport",
    "decode_embedded_artifact",
    "definition_has_embedded",
    "freeze_setup_definition",
    "local_component_identity",
    "resolve_source",
    "source_links_for_snapshot",
    "suggest_catalog_replacement",
    "try_parse_setup_definition",
    "unpack_component_tree",
    "validate_frozen_snapshot",
    "validate_setup_definition",
]
