import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Proves request/response types come from the generated contract client
 * (REQ-2211) and not a hand-maintained DTO set.
 */
describe("typed client provenance", () => {
  const generatedDir = path.resolve(__dirname, "../../src/lib/api/generated");

  it("generated types file exists and is marked auto-generated", () => {
    const types = readFileSync(path.join(generatedDir, "types.gen.ts"), "utf8");
    expect(types).toContain("auto-generated by @hey-api/openapi-ts");
    expect(types).toContain("export type ComponentSummary");
    expect(types).toContain("export type DeviceSummary");
    expect(types).toContain("export type AccountProfile");
  });

  it("sdk exports catalog and identity operations from openapi", () => {
    const sdk = readFileSync(path.join(generatedDir, "sdk.gen.ts"), "utf8");
    expect(sdk).toContain("searchComponents");
    expect(sdk).toContain("searchSetups");
    expect(sdk).toContain("readComponent");
    expect(sdk).toContain("readAccount");
    expect(sdk).toContain("listDevices");
    expect(sdk).toContain("revokeDevice");
  });

  it("sdk exports owner publication grant report and staff operations", () => {
    const sdk = readFileSync(path.join(generatedDir, "sdk.gen.ts"), "utf8");
    expect(sdk).toContain("listOwnerObjects");
    expect(sdk).toContain("readOwnerObject");
    expect(sdk).toContain("readOwnerVersion");
    expect(sdk).toContain("startOwnerPublication");
    expect(sdk).toContain("createPublicationPlan");
    expect(sdk).toContain("confirmPublicationPlan");
    expect(sdk).toContain("listGrants");
    expect(sdk).toContain("createGrantInvitation");
    expect(sdk).toContain("acceptGrantInvitation");
    expect(sdk).toContain("createReportCase");
    expect(sdk).toContain("listStaffReports");
    expect(sdk).toContain("staffTriageReport");
  });

  it("hand-written api modules import generated types only", () => {
    const catalog = readFileSync(path.resolve(__dirname, "../../src/lib/api/catalog.ts"), "utf8");
    expect(catalog).toContain('from "./generated/types.gen"');
    expect(catalog).not.toMatch(/type ComponentSummary = \{/);
    const owner = readFileSync(path.resolve(__dirname, "../../src/lib/api/owner.ts"), "utf8");
    expect(owner).toContain('from "@/lib/api/generated/types.gen"');
  });
});
